spring.datasource.url=jdbc:postgresql://localhost:5432/job_aggregator
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

adzuna.app.id=790e0a37
adzuna.app.key=90e9fb6b24501ae9e791eab4ad1ba710

